### ISSUE TITLE
GROUPS don't working

### ISSUE THREAD

**Issue by cantorthiagofelipe** [hyperdefined/TabCompleter#16]
I defined the groups, and which commands would be shown to the members of that group, but it's not working correctly!
Default group is working fine, but others don't
I'm using LUCK PERMS

![image](https://user-images.githubusercontent.com/102884950/205419686-7f03f1e4-5df4-4acb-8619-20ea7c71b176.png)
![image](https://user-images.githubusercontent.com/102884950/205419652-ada64445-0965-4d34-98f3-61dc5c1b1fa7.png)
![image](https://user-images.githubusercontent.com/102884950/205419657-f9286e61-b0ea-4bf6-ad64-c9bab4e67970.png)

**Comment by hyperdefined** [comment]
My group detection was working before, something must of broken it then. I need a better long term solution regardless. I will look into fixing this soon. Will probably require Vault on the new version for their API.

**Comment by hyperdefined** [comment]
I released the update to fix this: https://github.com/hyperdefined/TabCompleter/releases/tag/1.3.2

Make sure you have Vault installed!
