### ISSUE TITLE
Message Unknown command

### ISSUE THREAD

**Issue by ItzRonaldLG** [hyperdefined/TabCompleter#2]
Hello, 
If the message is client side and you cant remove it with plugins its no problem :)
If you think you fixed it, its not: https://prnt.sc/zgm5w0
Pl is of course not in the list from the plugin, but it is a command ;)

Let me know if it can/can't be changed with a plugin (Not a big problem if not)

**Comment by hyperdefined** [comment]
Sorry about the confusion, I thought you were having a different issue than I thought. The 1.1 update did fix an issue, which I thought you were having.

That message like I said shows on the client, the server can't remove it unfortunately.

**Comment by ItzRonaldLG** [comment]
No problem ;)
