### ISSUE TITLE
actually-block-command-execution | not working 

### ISSUE THREAD

**Issue by SNokerYT** [hyperdefined/TabCompleter#5]
this option not working
actually-block-command-execution

**Comment by hyperdefined** [comment]
I'll take a look at this later today when I have time. I did change the logic for that config option so something must of broken.

**Comment by hyperdefined** [comment]
Are commands not blocking or are you unable to change this config option? Because currently, it doesn't check the config for `actually-block-command-execution` and blocks the commands by default (this is going to be fixed).

**Comment by hyperdefined** [comment]
I went ahead and fixed the `actually-block-command-execution` config option. It now properly reactions to whatever it is set. Hopefully this will fix your issue. If not, then feel free to reopen this and we can discuss further.

Get the update here: https://github.com/hyperdefined/TabCompleter/releases/tag/1.3.1
