### ISSUE TITLE
Does this plugin support proxy - Velocity?

### ISSUE THREAD

**Issue by Nextinka** [hyperdefined/TabCompleter#8]
It would be really nice if it could, the plugin wouldn't have to be installed on each server instance. Would it actually be possible add this feature  if it hasn't been implemented into the plugin yet? Thanks.

**Comment by hyperdefined** [comment]
It currently does not, and I do not have plans currently. If I were to add proxy support, would it a global setting (commands are the same on every server) or individual bases (commands per server)?

**Comment by Nextinka** [comment]
Probably commands per server, that would be really nice as you wouldn't be forced to download the plugin on each backend. Velocity is not really famous and it does not support lots of plugins, this would probably be the first plugin doing something like this

**Comment by hyperdefined** [comment]
You can use this plugin if you really want something right now. It supports Velocity. However, it doesn't have groups or per server commands.

https://forums.papermc.io/threads/velocity-command-blocker-fully-block-commands-using-regex-and-permissions.114/
